### ISSUE TITLE
Issue in tracking

### ISSUE THREAD

**Issue by rabiaali95** [christian-rncl/TrackNPred#6]
I ran detection and tracking from scratch for TRAF13 dataset. Detection is done successfully but for tracking i am facing with the following error. Can you please guide how to get rid of this

finished detection for resources/data/TRAFF/TRAF13...
begin tracking for resources/data/TRAFF/TRAF13...
TRAF13
Processing TRAF13
2019-08-30 13:28:03.614975: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
DATASET densepeds: resources/data/TRAFF
Traceback (most recent call last):
  File "main_cmd.py", line 109, in <module>
    model.tracking(args.dir, DATA_FOLDER.format(i), False)
  File "/hdd/local/sda/rabia/TrackNPred/model/model.py", line 130, in tracking
    densepeds(dataDir, data_folder, display, thread)
  File "/hdd/local/sda/rabia/TrackNPred/model/Tracking/DensePeds.py", line 304, in densepeds
    run(sequence_dir, detection_file, output_file, matlab_file, min_conf, nms, min_det_ht, max_cos_dist, nn_budget, disp, thread)
  File "/hdd/local/sda/rabia/TrackNPred/model/Tracking/DensePeds.py", line 227, in run
    visualizer.run(frame_callback, thread)
TypeError: run() takes 2 positional arguments but 3 were given
(trackNpred) rabia@vivace-server:~/TrackNPred$

**Comment by rabiaali95** [comment]
and sometimes it stucks at this warning
TRAF13
Processing TRAF13
2019-08-30 13:41:20.092245: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.

**Comment by rabiaali95** [comment]
Also if i use the provided tracking then there is an error in generating formatted txt. The error is as follows
begin tracking for resources/data/TRAFF/TRAF13...
DATASET densepeds: resources/data/TRAFF
TRAF13 0.014071941375732422
finished tracking for resources/data/TRAFF/TRAF13...
Formatting resources/data/TRAFF/TRAF13 for prediction...
/hdd/local/sda/rabia/TrackNPred/model/Tracking/hypo_formatter.py:46: UserWarning: loadtxt: Empty input file: "<_io.TextIOWrapper name='resources/data/TRAFF/TRAF13/hypotheses.txt' mode='r' encoding='UTF-8'>"
  hypo_mtrx = np.loadtxt(f, delimiter=',')
Traceback (most recent call last):
  File "main_cmd.py", line 123, in <module>
    formatFile(hypo, i, formatted_hypo) 
  File "/hdd/local/sda/rabia/TrackNPred/model/Tracking/hypo_formatter.py", line 52, in formatFile
    formatted = getFormattedDF(inFilePath, dsetID)
  File "/hdd/local/sda/rabia/TrackNPred/model/Tracking/hypo_formatter.py", line 48, in getFormattedDF
    return formatHypo(dsetID, hypo_mtrx)
  File "/hdd/local/sda/rabia/TrackNPred/model/Tracking/hypo_formatter.py", line 34, in formatHypo
    formatted_df['vid_idx'] = list(hypo_mtrx[:,HYP_VID_IDX].astype(int))
IndexError: too many indices for array

How to solve this as well?

**Comment by rohanchandra30** [comment]
Thanks, we will get to this soon.

**Comment by rayguan97** [comment]
Now this issue is fixed.
